"""Shared translations for the painted application labels; data is never translated."""
language='BAHASA INDONESIA'
TEXTS={
 'DASHBOARD':'DASHBOARD','TAHAP 1 / BOX':'STAGE 1 / BOX','TAHAP 2 / CARTON':'STAGE 2 / CARTON',
 'TAHAP 3 / PALLET':'STAGE 3 / PALLET','REVISION':'REVISION','KIRIM DATA':'SEND DATA','PENGATURAN':'SETTINGS',
 'MASTER TEMPLATE':'MASTER TEMPLATE','MONITORING & RINGKASAN PROSES AGREGASI':'AGGREGATION MONITORING & SUMMARY',
 'PEMINDAHAN & VERIFIKASI UNIT PRODUK':'PRODUCT UNIT TRANSFER & VERIFICATION','PENYUSUNAN BOX KE CARTON':'BOX TO CARTON AGGREGATION',
 'PENYUSUNAN CARTON KE PALLET':'CARTON TO PALLET AGGREGATION','REVISION DATA & PENELUSURAN AGREGASI':'DATA REVISION & TRACEABILITY',
 'SINKRONISASI & PENGIRIMAN DATA':'DATA SYNCHRONIZATION & DELIVERY','TOTAL UNIT HARI INI':'TOTAL UNITS TODAY',
 'RINGKASAN TAHAP AGREGASI':'AGGREGATION STAGE SUMMARY','MONITORING PRODUK AKTIF':'ACTIVE PRODUCT MONITORING',
 'GRAFIK PRODUKSI / PROGRES SHIFT':'PRODUCTION CHART / SHIFT PROGRESS','AKTIVITAS TERKINI (SEMUA MODUL)':'RECENT ACTIVITY (ALL MODULES)',
 'STATUS PERANGKAT & KONEKSI':'DEVICES & CONNECTIONS','AKSI CEPAT':'QUICK ACTIONS','PROSES SELESAI':'PROCESS COMPLETE',
 'PRODUK':'PRODUCT','PRODUK AKTIF':'ACTIVE PRODUCT','BOX SAAT INI':'CURRENT BOX','CARTON SAAT INI':'CURRENT CARTON',
 'PALLET SAAT INI':'CURRENT PALLET','PERIODE':'PERIOD','WAKTU':'TIME','MODUL':'MODULE','KETERANGAN':'DESCRIPTION',
 'DUPLIKAT':'DUPLICATE','SELESAI':'COMPLETE','TOTAL AGREGASI HARI INI':'TOTAL AGGREGATION TODAY',
 'RINGKASAN UMUM':'GENERAL SUMMARY','AKTIVITAS TERKINI':'RECENT ACTIVITY','KONEKSI DATABASE':'DATABASE CONNECTION',
 'KAMERA VERIFIKASI':'VERIFICATION CAMERA','INFORMASI SISTEM':'SYSTEM INFORMATION','AKUN LOGIN':'CURRENT ACCOUNT',
 'SHORTCUT KONEKSI':'CONNECTION SHORTCUTS','DATA TARGET':'TARGET DATA','VERIFIKASI KAMERA':'CAMERA VERIFICATION',
 'AGREGASI UNIT KE BOX':'UNIT TO BOX AGGREGATION','AGREGASI BOX KE CARTON':'BOX TO CARTON AGGREGATION',
 'AGREGASI CARTON KE PALLET':'CARTON TO PALLET AGGREGATION','PROGRES AGREGASI':'AGGREGATION PROGRESS',
 'PILIH PRODUK / BATCH / LIST DATA':'SELECT PRODUCT / BATCH / DATA LIST','DATA SCAN • 5 TERAKHIR':'LATEST 5 SCANS',
 'HASIL AGREGASI BOX':'BOX AGGREGATION RESULTS','HASIL AGREGASI CARTON':'CARTON AGGREGATION RESULTS',
 'HASIL AGREGASI PALLET':'PALLET AGGREGATION RESULTS','KONTROL LINE':'LINE CONTROL','KUNCI BOX':'LOCK BOX',
 'KUNCI CARTON':'LOCK CARTON','KUNCI PALLET':'LOCK PALLET','TANGGAL':'DATE','KODE BOX':'BOX CODE','KODE CARTON':'CARTON CODE',
 'KODE PALLET':'PALLET CODE','CARI DATA':'SEARCH DATA','HASIL PENCARIAN / DATA AGREGASI':'SEARCH RESULTS / AGGREGATION DATA',
 'DETAIL DATA TERPILIH':'SELECTED RECORD DETAILS','RIWAYAT TRACEABILITY':'TRACEABILITY HISTORY','AKSI REVISION':'REVISION ACTIONS',
 'LOG REVISION':'REVISION LOG','ANTREAN DATA SIAP KIRIM':'OUTBOUND DATA QUEUE','STATUS SINKRONISASI':'SYNCHRONIZATION STATUS',
 'PROGRES SINKRONISASI':'SYNCHRONIZATION PROGRESS','PILIH DATA & FILTER':'SELECT DATA & FILTER','RIWAYAT PENGIRIMAN':'DELIVERY HISTORY',
 'KIRIM SEKARANG':'SEND NOW','RETRY GAGAL':'RETRY FAILED','BERHASIL DIKIRIM':'DELIVERED','GAGAL':'FAILED',
 'PILIH SEMUA':'SELECT ALL','VALIDASI':'VALIDATE','LIHAT SEMUA  ›':'VIEW ALL  ›','KAMERA':'CAMERA',
 'BUKA TAHAP 1':'OPEN STAGE 1','BUKA TAHAP 2':'OPEN STAGE 2','BUKA TAHAP 3':'OPEN STAGE 3',
}
def set_language(value,extra=None):
    global language
    language=value
    if extra:TEXTS.update(extra)
def translate(text):
    return TEXTS.get(text,text) if language=='ENGLISH' else text
